## To find companies in which Venture Capitalist Fund would invest based on various attributes
#### Created a model to predict profit based on R&D Spend, Marketing Spend, location, etc
###### Dataset consists of information regarding startup companies

In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Importing the dataset

In [3]:
dataset = pd.read_csv('data/50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,4].values

dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

- Encoding categorical data
- Encoding the Independent Variable

In [4]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

X[:1]

array([[  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.65349200e+05,   1.36897800e+05,   4.71784100e+05]])

Avoiding Dumy Variable Trap

In [5]:
X = X[:,1:]
X[:1]

array([[  0.00000000e+00,   1.00000000e+00,   1.65349200e+05,
          1.36897800e+05,   4.71784100e+05]])

Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)


c:\users\patel\appdata\local\programs\python\python36\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


#### Multiple Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train,y_train)

#Predicting the Test set Result

y_pred = regressor.predict(X_test)
y_pred

array([ 103015.20159796,  132582.27760816,  132447.73845175,
         71976.09851259,  178537.48221054,  116161.24230163,
         67851.69209676,   98791.73374688,  113969.43533012,
        167921.0656955 ])

In [8]:
Compare = pd.DataFrame({'Prediction':y_pred,'Actual':y_test})
Compare['Prediction'] = pd.Series([round(val,2) for val in Compare['Prediction']])
Compare

Actual  Prediction
0  103282.38   103015.20
1  144259.40   132582.28
2  146121.95   132447.74
3   77798.83    71976.10
4  191050.39   178537.48
5  105008.31   116161.24
6   81229.06    67851.69
7   97483.56    98791.73
8  110352.25   113969.44
9  166187.94   167921.07